codeFirstNet/Models/ErrorViewModel.cs
namespace codeFirstNet.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

codeFirstNet/Models/Produit.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace codeFirstNet.Models
{
    public class Produit
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        [Required]
        public string titre { get; set; }

        [Required]
        public string categorie { get; set; }

        [Required]
        public int quantite { get; set; }

        [Required]
        public string description { get; set; }

    }
}

codeFirstNet/Models/ProduitCommand.cs
namespace codeFirstNet.Models
{
    public class ProduitCommand
    {

        public int idCommand { get; set; }

        public string titreCommand { get; set; }

        public string categorieCommand { get; set; }

        public int quantiteCommand { get; set; }

        public string descriptionCommand { get; set; }
    }
}

codeFirstNet/Controllers/HomeController.cs
using codeFirstNet.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace codeFirstNet.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

codeFirstNet/Controllers/ProduitController.cs
using codeFirstNet.Data;
using codeFirstNet.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace codeFirstNet.Controllers
{
    public class ProduitController : Controller
    {
        private ProduitContext produitContext;

        public ProduitController(ProduitContext produitContext)
        {
            this.produitContext = produitContext;
        }




        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> Add(ProduitCommand produitCommand)
        {
            Produit produit = new Produit
            {
                titre = produitCommand.titreCommand,
                categorie = produitCommand.categorieCommand,
                quantite = produitCommand.quantiteCommand,
                description = produitCommand.descriptionCommand,
            };
            await produitContext.produits.AddAsync(produit);
            await produitContext.SaveChangesAsync();

            return RedirectToAction("List");
        }



        [HttpGet]
        public async Task<IActionResult> List()
        {
            var produits = await produitContext.produits.ToListAsync();
            return View(produits);
        }







        [HttpGet]
        public async Task<IActionResult> GetUpdate(int id)
        {
            var produit = await produitContext.produits.FirstOrDefaultAsync(p => p.id == id);
            if(produit != null)
            {
                ProduitCommand produitCommand = new ProduitCommand
                {
                    idCommand = produit.id,
                    titreCommand = produit.titre,
                    categorieCommand = produit.categorie,
                    quantiteCommand = produit.quantite,
                    descriptionCommand = produit.description,
                };

                return View(produitCommand);
            }
            return RedirectToAction("List");
        }


        [HttpPost]
        public async Task<IActionResult> GetUpdate(ProduitCommand produitCommand)
        {
            var produit = await produitContext.produits.FindAsync(produitCommand.idCommand);
            if (produit != null)
            {
                produit.titre = produitCommand.titreCommand;   
                produit.categorie = produitCommand.categorieCommand;
                produit.quantite = produitCommand.quantiteCommand;
                produit.description = produitCommand.descriptionCommand;
                await produitContext.SaveChangesAsync();
                return RedirectToAction("List");
            }
            return RedirectToAction("List");
        }



        [HttpGet]
        public async Task<IActionResult> GetDelete(int id)
        {
            var produit = await produitContext.produits.FirstOrDefaultAsync(p => p.id == id);
            if (produit != null)
            {
                return View(produit);
            }
            return RedirectToAction("List");
        }



        [HttpPost]
        public async Task<IActionResult> GetDelete(Produit produit)
        {
            var produitDelete = await produitContext.produits.FindAsync(produit.id);
            if (produitDelete != null)
            {
                produitContext.produits.Remove(produitDelete);
                await produitContext.SaveChangesAsync();
                return RedirectToAction("List");
            }
            return RedirectToAction("List");
        }


        [HttpPost]
        public async Task<ActionResult> Search(string search)
        {
            var produit = await produitContext.produits.Where(p => p.id.ToString() == search || p.titre.Contains(search) ).ToListAsync();
            if (produit != null) {
            return View("List", produit);
            }
            else
            {
            return View("List", null);

            }
        }
    }
}

codeFirstNet/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Gerez votre stock de produits !</p>
</div>

codeFirstNet/Views/Produit/Add.cshtml
@model ProduitCommand


@{
}

<h2 class="mt-5">Ajouter un nouveau produit</h2>

<form method="post" action="Add" class="mt-5">
    <div class="mb-3">
        <label class="form-label">Titre</label>
        <input type="text" class="form-control" asp-for="titreCommand">
    </div>
    <div class="mb-3">
        <label class="form-label">Catégorie</label>
        <input type="text" class="form-control" asp-for="categorieCommand">
    </div>
    <div class="mb-3">
        <label class="form-label">Quantité</label>
        <input type="number" class="form-control" asp-for="quantiteCommand">
    </div>
    <div class="mb-3">
        <label class="form-label">Description</label>
        <input type="text" class="form-control" asp-for="descriptionCommand">
    </div>

    <button type="submit" class="btn btn-primary">Ajouter</button>
    <a asp-action="List" class="btn btn-primary m-md-1">Retour</a>

</form>

codeFirstNet/Views/Produit/GetDelete.cshtml
@model Produit



@{
}

<div class="d-flex align-items-center justify-content-center" style="min-height: 70vh;">
    <div class="card bg-dark " style="width: 18rem; padding: 35px;">
    <div class="card-body text-center ">
        <h5 class="card-title text-light mb-4">Etes-vous sur de vouloir supprimer @Model.titre ?</h5>
            <form asp-action="GetDelete" asp-route-id="@Model.id" method="post">
                <button type="submit" class="btn btn-danger m-lg-1">Oui</button>
                <a asp-action="List" class="btn btn-primary m-md-1">Non</a>
            </form>
    </div>
    </div>
</div>

codeFirstNet/Views/Produit/GetUpdate.cshtml
@model ProduitCommand


@{
}

<h2 class="mt-5">Modifier un produit</h2>

<form method="post" action="GetUpdate" class="mt-5">
    <div class="mb-3">
        <label class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="idCommand" readonly>
    </div>
    <div class="mb-3">
        <label class="form-label">Titre</label>
        <input type="text" class="form-control" asp-for="titreCommand">
    </div>
    <div class="mb-3">
        <label class="form-label">Catégorie</label>
        <input type="text" class="form-control" asp-for="categorieCommand">
    </div>
    <div class="mb-3">
        <label class="form-label">Quantité</label>
        <input type="number" class="form-control" asp-for="quantiteCommand">
    </div>
    <div class="mb-3">
        <label class="form-label">Description</label>
        <input type="text" class="form-control" asp-for="descriptionCommand">
    </div>

    <button type="submit" class="btn btn-primary">Sauvegarder</button>
    <a asp-action="List" class="btn btn-primary m-md-1">Retour</a>

</form>

codeFirstNet/Views/Produit/List.cshtml
@model List<Produit>



<h2 class="mt-5 mb-5">Produits</h2>

@if (Model == null || Model.Count == 0)
{
    <p>Aucun produit trouvé.</p>
}
else
{
    <table class="table text-light">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Titre</th>
                <th scope="col">Catégorie</th>
                <th scope="col">Quantité</th>
                <th scope="col">Description</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var produit in Model)
            {
                <tr>
                    <th scope="row">@produit.id</th>
                    <td>@produit.titre.First().ToString().ToUpper()@produit.titre.Substring(1)</td>
                    <td>@produit.categorie.First().ToString().ToUpper()@produit.categorie.Substring(1)</td>
                    <td>@produit.quantite</td>
                    <td>@produit.description.First().ToString().ToUpper()@produit.description.Substring(1)</td>
                    <td>
                        <a class="btn btn-primary" href="GetUpdate/@produit.id">Modifier</a>
                        <a class="btn ml-0 btn-danger" href="GetDelete/@produit.id">Supprimer</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

codeFirstNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>StockNet</title>
     <link rel="icon" href="~/person-icon.png" type="image/png" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/codeFirstNet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">StockNet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Produit" asp-action="List">Produits</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Produit" asp-action="Add">Add product</a>
                        </li>
                    </ul>
                    <div class="ml-auto">
                        <form class="form-inline my-2 my-lg-0" method="post" asp-controller="Produit" asp-action="Search">
                            <div class="input-group">
                                <input class="form-control mr-sm-2" type="search" placeholder="Search..." aria-label="Search" name="Search" />
                                <div class="input-group-append">
                                    <button class="btn btn-outline-success" type="submit">Search</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - codeFirstNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>